<?php
    if(session_status() != 2) {
        session_start();
    }
    $itemController = new ItemController();
    $authCheck = new Authorisation();
?>

<svg xmlns='http://www.w3.org/2000/svg' style='display: none;'>
      <symbol id='check-circle-fill' fill='currentColor' viewBox='0 0 16 16'>
        <path d='M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zm-3.97-3.03a.75.75 0 0 0-1.08.022L7.477 9.417 5.384 7.323a.75.75 0 0 0-1.06 1.06L6.97 11.03a.75.75 0 0 0 1.079-.02l3.992-4.99a.75.75 0 0 0-.01-1.05z'></path>
      </symbol>
      <symbol id='info-fill' fill='currentColor' viewBox='0 0 16 16'>
        <path d='M8 16A8 8 0 1 0 8 0a8 8 0 0 0 0 16zm.93-9.412-1 4.705c-.07.34.029.533.304.533.194 0 .487-.07.686-.246l-.088.416c-.287.346-.92.598-1.465.598-.703 0-1.002-.422-.808-1.319l.738-3.468c.064-.293.006-.399-.287-.47l-.451-.081.082-.381 2.29-.287zM8 5.5a1 1 0 1 1 0-2 1 1 0 0 1 0 2z'></path>
      </symbol>
      <symbol id='exclamation-triangle-fill' fill='currentColor' viewBox='0 0 16 16'>
        <path d='M8.982 1.566a1.13 1.13 0 0 0-1.96 0L.165 13.233c-.457.778.091 1.767.98 1.767h13.713c.889 0 1.438-.99.98-1.767L8.982 1.566zM8 5c.535 0 .954.462.9.995l-.35 3.507a.552.552 0 0 1-1.1 0L7.1 5.995A.905.905 0 0 1 8 5zm.002 6a1 1 0 1 1 0 2 1 1 0 0 1 0-2z'></path>
      </symbol>
</svg>

<div class='d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom'>
            <h1 class='h2' >Item hinzufügen</h1>
            <div class='btn-toolbar mb-2 mb-md-0'>
            <div class='btn-group me-2'>  
                <a href='?view=items'><button type='button' class='btn btn-sm btn-outline-secondary'>Zurück</button></a>
            </div>
            </div>
</div>

<?php

    // Feedback: Based on status code that Emp Controller returnes, diffrent messages will be displayed..

    if(isset($_SESSION['create_item_status']) && $_SESSION['create_item_status'] == 1){
      echo     "<div class='alert alert-success d-flex alert-dismissible fade show align-items-center' role='alert'>
      <svg class='bi flex-shrink-0 me-2' width='24' height='24' role='img' aria-label='Success:'><use xlink:href='#check-circle-fill'></use></svg>
      <div>
        Item wurde erfolgreich hinzugefügt!
      </div>
      <button type='button' class='btn-close' data-bs-dismiss='alert' aria-label='Close'></button>
    </div>";
    unset($_SESSION['create_item_status']);
    }
    if(isset($_SESSION['create_item_status']) && $_SESSION['create_item_status'] == 0){
      echo     "<div class='alert alert-danger d-flex alert-dismissible fade show align-items-center' role='alert'>
      <svg class='bi flex-shrink-0 me-2' width='24' height='24' role='img' aria-label='Danger:'><use xlink:href='#exclamation-triangle-fill'/></svg>
      <div>
      Item konnte nicht hinzugefügt werden..
      </div>
      <button type='button' class='btn-close' data-bs-dismiss='alert' aria-label='Close'></button>
    </div>";
    unset($_SESSION['create_item_status']);
    }
    if(isset($_SESSION['create_item_status']) && $_SESSION['create_item_status'] == 2){
      echo     "<div class='alert alert-warning d-flex alert-dismissible fade show align-items-center' role='alert'>
      <svg class='bi flex-shrink-0 me-2' width='24' height='24' role='img' aria-label='Warning:'><use xlink:href='#exclamation-triangle-fill'/></svg>
      <div>
        Sie sind leider nicht berechtigt ein Item hinzuzufügen..
      </div>
      <button type='button' class='btn-close' data-bs-dismiss='alert' aria-label='Close'></button>
    </div>";
    unset($_SESSION['create_item_status']);
    }
    if(isset($_SESSION['validation']) && $_SESSION['validation'] == 0){
      echo     "<div class='alert alert-warning d-flex alert-dismissible fade show align-items-center' role='alert'>
      <svg class='bi flex-shrink-0 me-2' width='24' height='24' role='img' aria-label='Warning:'><use xlink:href='#exclamation-triangle-fill'/></svg>
      <div>
        Bitte füllen Sie alle Felder aus und verwenden Sie keine Sonderzeichen.
      </div>
      <button type='button' class='btn-close' data-bs-dismiss='alert' aria-label='Close'></button>
    </div>";
    unset($_SESSION['validation']);
    }

 

   if($authCheck->checkAuthorisation("items_create") == 0){
    echo "<div class='alert alert-warning' role='alert'>
    Sie haben keine Berechtigung diese Seite aufzurufen.
    </div>";
  }else{
  echo "<form method='post' action='View/php/helper/helper_itemcreate.php'>
  <div class='mb-3'>
    <label for='item_type' class='form-label' data-bs-toggle='tooltip' data-bs-placement='right' title='Geben Sie den Typ oder die Art des Items an (z.B. Schlüssel oder Computer)'>Typ des Items <span data-feather='info' class='align-text-bottom'></span></label>
    <input type='text' class='form-control' id='item_type' name='item_type' placeholder='Beispiel: Computer'>
  </div>
  <div class='mb-3'>
    <label for='item_factory' class='form-label' data-bs-toggle='tooltip' data-bs-placement='right' title='Geben Sie eine Identifikation oder eine Herstellernummer an (z.B. Seriennummer des Computers oder Schlüsselnummer'>Identifikation oder Herstellernummer <span data-feather='info' class='align-text-bottom'></span></label>
    <input type='text' class='form-control' id='item_factory' name='item_factory' placeholder='Beispiel: SN201932'>
  </div>
  <div class='mb-3'>
    <label for='item_name' class='form-label' data-bs-toggle='tooltip' data-bs-placement='right' title='Geben Sie dem Item einen Namen oder geben Sie den Hersteller an (z.B. Hostname oder Schlüsselhersteller)'>Name oder Hersteller <span data-feather='info' class='align-text-bottom'></span></label>
    <input type='text' class='form-control' id='item_name' name='item_name' placeholder='Beispiel: PC200291'>
  </div>
  <button type='submit' class='btn btn-success'>Item hinzufügen</button>
  </form>";
  }
?>
