<?php
if(session_status() != 2) {
    session_start();
}
$user = new User();
$authCheck = new Authorisation();

?>
<svg xmlns='http://www.w3.org/2000/svg' style='display: none;'>
      <symbol id='check-circle-fill' fill='currentColor' viewBox='0 0 16 16'>
        <path d='M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zm-3.97-3.03a.75.75 0 0 0-1.08.022L7.477 9.417 5.384 7.323a.75.75 0 0 0-1.06 1.06L6.97 11.03a.75.75 0 0 0 1.079-.02l3.992-4.99a.75.75 0 0 0-.01-1.05z'></path>
      </symbol>
      <symbol id='info-fill' fill='currentColor' viewBox='0 0 16 16'>
        <path d='M8 16A8 8 0 1 0 8 0a8 8 0 0 0 0 16zm.93-9.412-1 4.705c-.07.34.029.533.304.533.194 0 .487-.07.686-.246l-.088.416c-.287.346-.92.598-1.465.598-.703 0-1.002-.422-.808-1.319l.738-3.468c.064-.293.006-.399-.287-.47l-.451-.081.082-.381 2.29-.287zM8 5.5a1 1 0 1 1 0-2 1 1 0 0 1 0 2z'></path>
      </symbol>
      <symbol id='exclamation-triangle-fill' fill='currentColor' viewBox='0 0 16 16'>
        <path d='M8.982 1.566a1.13 1.13 0 0 0-1.96 0L.165 13.233c-.457.778.091 1.767.98 1.767h13.713c.889 0 1.438-.99.98-1.767L8.982 1.566zM8 5c.535 0 .954.462.9.995l-.35 3.507a.552.552 0 0 1-1.1 0L7.1 5.995A.905.905 0 0 1 8 5zm.002 6a1 1 0 1 1 0 2 1 1 0 0 1 0-2z'></path>
      </symbol>
</svg>

<div class='d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom'>
            <h1 class='h2'>Benutzer hinzufügen</h1>
            <div class='btn-toolbar mb-2 mb-md-0'>
            <div class='btn-group me-2'>  
                <a href='?view=users'><button type='button' class='btn btn-sm btn-outline-secondary'>Zurück</button></a>
            </div>
            </div>
</div>

<?php
    if(isset($_SESSION['create_user_status']) && $_SESSION['create_user_status'] == 1){
      echo     "<div class='alert alert-success d-flex alert-dismissible fade show align-items-center' role='alert'>
      <svg class='bi flex-shrink-0 me-2' width='24' height='24' role='img' aria-label='Success:'><use xlink:href='#check-circle-fill'></use></svg>
      <div>
        Benutzer wurde erfolgreich hinzugefügt!
      </div>
      <button type='button' class='btn-close' data-bs-dismiss='alert' aria-label='Close'></button>
    </div>";
    unset($_SESSION['create_user_status']);
    }
    if(isset($_SESSION['create_user_status']) && $_SESSION['create_user_status'] == 0){
      echo     "<div class='alert alert-danger d-flex alert-dismissible fade show align-items-center' role='alert'>
      <svg class='bi flex-shrink-0 me-2' width='24' height='24' role='img' aria-label='Danger:'><use xlink:href='#exclamation-triangle-fill'/></svg>
      <div>
        Benutzer konnte nicht hinzugefügt werden..
      </div>
      <button type='button' class='btn-close' data-bs-dismiss='alert' aria-label='Close'></button>
    </div>";
    unset($_SESSION['create_user_status']);
    }
    if(isset($_SESSION['create_user_status']) && $_SESSION['create_user_status'] == 2){
      echo     "<div class='alert alert-warning d-flex alert-dismissible fade show align-items-center' role='alert'>
      <svg class='bi flex-shrink-0 me-2' width='24' height='24' role='img' aria-label='Warning:'><use xlink:href='#exclamation-triangle-fill'/></svg>
      <div>
        Sie sind leider nicht berechtigt einen Benutzer hinzuzufügen..
      </div>
      <button type='button' class='btn-close' data-bs-dismiss='alert' aria-label='Close'></button>
    </div>";
    unset($_SESSION['create_user_status']);
    }
    if(isset($_SESSION['validation']) && $_SESSION['validation'] == 0){
      echo     "<div class='alert alert-warning d-flex alert-dismissible fade show align-items-center' role='alert'>
      <svg class='bi flex-shrink-0 me-2' width='24' height='24' role='img' aria-label='Warning:'><use xlink:href='#exclamation-triangle-fill'/></svg>
      <div>
        Bitte füllen Sie alle Felder aus und verwenden Sie keine Sonderzeichen.
      </div>
      <button type='button' class='btn-close' data-bs-dismiss='alert' aria-label='Close'></button>
    </div>";
    unset($_SESSION['validation']);
    }

    if($authCheck->checkAuthorisation("user_edit") == 0){
      echo "<div class='alert alert-warning' role='alert'>
      Sie haben keine Berechtigung diese Seite aufzurufen.
      </div>";
    }else{ 
      echo "<form method='POST' action='View/php/helper/helper_usercreate.php'>
      <div class='mb-3'>
        <label for='name' class='form-label'>Vorname</label>
        <input type='text' class='form-control' id='name' name='name' placeholder='Max'>
      </div>
      <div class='mb-3'>
        <label for='fname' class='form-label'>Nachname</label>
        <input type='text' class='form-control' id='fname' name='fname' placeholder='Mustermann'>
      </div>
      <div class='mb-3'>
        <label for='username' class='form-label'>Benutzername (E-Mail)</label>
        <input type='text' class='form-control' id='username' name='username' placeholder='Max.Mustermann@mitems.com'>
      </div>
      <div class='mb-3'>
        <label for='password' class='form-label'>Passwort</label>
        <input type='password' class='form-control' id='password' name='password' placeholder='******'>
      </div>
      <label for='formGroupExampleInput' class='form-label'>Rollen</label>
      <div class='form-check'>
        <input class='form-check-input' type='checkbox' value='1' id='role_user' name='role_user' checked>
        <label class='form-check-label' for='role_user'>
          User
        </label>
      </div>
      <div class='form-check'>
        <input class='form-check-input' type='checkbox' value='2' id='role_hr' name='role_hr' >
        <label class='form-check-label' for='role_hr'>
          HR
        </label>
      </div>
      <div class='form-check'>
        <input class='form-check-input' type='checkbox' value='3' id='role_manager' name='role_manager' >
        <label class='form-check-label' for='role_manager'>
          Manager
        </label>
      </div>
      <div class='form-check'>
        <input class='form-check-input' type='checkbox' value='4' id='role_itemadmin' name='role_itemadmin' >
        <label class='form-check-label' for='role_itemadmin'>
          Item Admin
        </label>
      </div>
      <div class='form-check'>
        <input class='form-check-input' type='checkbox' value='5' id='role_plattformadmin' name='role_plattformadmin' >
        <label class='form-check-label' for='role_plattformadmin'>
          Plattform Admin
        </label>
      </div>
      <button type='submit' class='btn btn-success' style='margin-top:10px;'>Benutzer hinzufügen</button>
    </form>";
    }
?>

