<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
            <h1 class="h2">Mitarbeiter</h1>
            <div class="btn-toolbar mb-2 mb-md-0">
            <div class="btn-group me-2">  
                <a href="?view=createemp" class="btn btn-sm btn-outline-secondary">Mitarbeiter hinzufügen</a>
                <a href="View/php/helper/helper_data_export.php?type=emp" class="btn btn-sm btn-outline-secondary">Export</a>
            </div>
            </div>
</div>

<div class="table-responsive">
            <table class="table table-striped table-sm" id="emp_table">
            <thead>
                <tr>
                <th scope="col">ID</th>
                <th scope="col">Nachname</th>
                <th scope="col">Vorname</th>
                <th scope="col">Abteilung</th>
                <th scope="col">Funktion</th>
                <th scope="col">E-Mail</th>
                <th scope="col">Vorgesetzter</th>
                <th scope="col">Eintritt</th>
                <th scope="col">Austritt</th>
                <th scope="col"> </th>
                </tr>
            </thead>
            <tbody>
            <?php
            $empController = new EmpController();
            $authCheck = new Authorisation();
            $result = $empController->getAllEmployees();
            while(odbc_fetch_row($result)) {
                echo "<tr>";
                echo"<td>".odbc_result($result, "id")."</td>
                    <td>".odbc_result($result, "sname")."</td>
                    <td>".odbc_result($result, "fname")."</td>
                    <td>".odbc_result($result, "department")."</td>
                    <td>".odbc_result($result, "function")."</td>
                    <td>".odbc_result($result, "email")."</td>
                    <td>".odbc_result($result, "manager")."</td>
                    <td>".odbc_result($result, "start")."</td>
                    <td>".odbc_result($result, "end")."</td>";

                if($authCheck->checkAuthorisation("emp_edit") == 1){
                    echo "<td><a href='?view=editemp&id=".odbc_result($result, "id")."' class='btn btn-info'>Bearbeiten</a></td>";
                }
                echo "</tr>";
            }
            
            ?>

            </tbody>
            </table>
</div>