<?php
    if(session_status() != 2) {
        session_start();
    }
    $empController = new EmpController();
    $itemController = new ItemController();
    $authCheck = new Authorisation();
?>

<svg xmlns='http://www.w3.org/2000/svg' style='display: none;'>
      <symbol id='check-circle-fill' fill='currentColor' viewBox='0 0 16 16'>
        <path d='M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zm-3.97-3.03a.75.75 0 0 0-1.08.022L7.477 9.417 5.384 7.323a.75.75 0 0 0-1.06 1.06L6.97 11.03a.75.75 0 0 0 1.079-.02l3.992-4.99a.75.75 0 0 0-.01-1.05z'></path>
      </symbol>
      <symbol id='info-fill' fill='currentColor' viewBox='0 0 16 16'>
        <path d='M8 16A8 8 0 1 0 8 0a8 8 0 0 0 0 16zm.93-9.412-1 4.705c-.07.34.029.533.304.533.194 0 .487-.07.686-.246l-.088.416c-.287.346-.92.598-1.465.598-.703 0-1.002-.422-.808-1.319l.738-3.468c.064-.293.006-.399-.287-.47l-.451-.081.082-.381 2.29-.287zM8 5.5a1 1 0 1 1 0-2 1 1 0 0 1 0 2z'></path>
      </symbol>
      <symbol id='exclamation-triangle-fill' fill='currentColor' viewBox='0 0 16 16'>
        <path d='M8.982 1.566a1.13 1.13 0 0 0-1.96 0L.165 13.233c-.457.778.091 1.767.98 1.767h13.713c.889 0 1.438-.99.98-1.767L8.982 1.566zM8 5c.535 0 .954.462.9.995l-.35 3.507a.552.552 0 0 1-1.1 0L7.1 5.995A.905.905 0 0 1 8 5zm.002 6a1 1 0 1 1 0 2 1 1 0 0 1 0-2z'></path>
      </symbol>
</svg>

<?php
    $resultEmployee = $empController->getEmployeeBasedOnId($_GET['id']);
    
?>

<div class='d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom'>
            <h1 class='h2'><?php echo "Items von ".odbc_result($resultEmployee, "fname").", ".odbc_result($resultEmployee, "sname"); ?></h1>
            <div class='btn-toolbar mb-2 mb-md-0'>
            <div class='btn-group me-2'>
            <?php echo "<a href='?view=assignitem&id=".$_GET['id']."' class='btn btn-sm btn-outline-secondary'>Item zuweisen</a>"; ?>
            <?php echo "<a href='View/php/helper/helper_data_export.php?type=empitems&id=".$_GET['id']."' class='btn btn-sm btn-outline-secondary'>Export</a>"; ?>
                <a href='?view=myemp' class='btn btn-sm btn-outline-secondary'>Zurück</a>
            </div>
            </div>
</div>

<?php
            $itemController = new ItemController();
            $authCheck = new Authorisation();
            $username = $_SESSION['userobj'];
            $result = $itemController->getMyItems(odbc_result($resultEmployee, "email"));

            if(isset($_SESSION['disassign_item_status']) && $_SESSION['disassign_item_status'] == 1){
                echo     "<div class='alert alert-success d-flex alert-dismissible fade show align-items-center' role='alert'>
                <svg class='bi flex-shrink-0 me-2' width='24' height='24' role='img' aria-label='Success:'><use xlink:href='#check-circle-fill'></use></svg>
                <div>
                  Item wurde erfolgreich als zurückgenommen erfasst!
                </div>
                <button type='button' class='btn-close' data-bs-dismiss='alert' aria-label='Close'></button>
              </div>";
              unset($_SESSION['disassign_item_status']);
              }
              if(isset($_SESSION['disassign_item_status']) && $_SESSION['disassign_item_status'] == 0){
                echo     "<div class='alert alert-danger d-flex alert-dismissible fade show align-items-center' role='alert'>
                <svg class='bi flex-shrink-0 me-2' width='24' height='24' role='img' aria-label='Danger:'><use xlink:href='#exclamation-triangle-fill'/></svg>
                <div>
                Item konnte nicht zurückgenommen werden..
                </div>
                <button type='button' class='btn-close' data-bs-dismiss='alert' aria-label='Close'></button>
              </div>";
              unset($_SESSION['disassign_item_status']);
              }
              if(isset($_SESSION['disassign_item_status']) && $_SESSION['disassign_item_status'] == 2){
                echo     "<div class='alert alert-warning d-flex alert-dismissible fade show align-items-center' role='alert'>
                <svg class='bi flex-shrink-0 me-2' width='24' height='24' role='img' aria-label='Warning:'><use xlink:href='#exclamation-triangle-fill'/></svg>
                <div>
                  Sie sind leider nicht berechtigt ein Item als zurückgenommen zu erfassen..
                </div>
                <button type='button' class='btn-close' data-bs-dismiss='alert' aria-label='Close'></button>
              </div>";
              unset($_SESSION['disassign_item_status']);
              }

            if(odbc_num_rows($result) == 0){
              echo "<div class='alert alert-warning' role='alert'>
              Dem Mitarbeiter sind keine Items zugewiesen
              </div>";
            }
            else
            {
              echo "<div class='table-responsive'>
              <table class='table table-striped table-sm' id='emp_table'>
              <thead>
                  <tr>
                  <th scope='col'>Typ</th>
                  <th scope='col'>Identifikation</th>
                  <th scope='col'>Name / Hersteller</th>
                  <th scope='col'>Zugewiesen am</th>
                  <th scope='col'>Retourniert am</th>
                  <th scope='col'>Status</th>
                  <th></th>
                  </tr>
              </thead>
              <tbody>";
           
            while(odbc_fetch_row($result)) {
                echo "<tr>";
                echo"<td>".odbc_result($result, "type")."</td>
                    <td>".odbc_result($result, "factorynr")."</td>
                    <td>".odbc_result($result, "name")."</td>
                    <td>".odbc_result($result, "recieved")."</td>
                    <td>".odbc_result($result, "returned")."</td>
                    <td>".odbc_result($result, "status")."</td>";
                    if($authCheck->checkAuthorisation("items_assign") == 1){
                        if(odbc_result($result, "status") == "Abgegeben"){
                            echo "<td><a href='#' class='btn btn-info disabled'>Item zurücknehmen</a></td>";
                        }else{
                            echo "<td><a href='View/php/helper/helper_disassign_item.php?id=".odbc_result($result, "id")."&empid=".$_GET['id']."' class='btn btn-info'>Item zurücknehmen</a></td>";
                        }
                        
                    }
                    echo "</tr>";
            }
          }
            ?>