<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
            <h1 class="h2">Items</h1>
            <div class="btn-toolbar mb-2 mb-md-0">
            <div class="btn-group me-2">  
                <a href="?view=createitem"><button type="button" class="btn btn-sm btn-outline-secondary">Item hinzufügen</button></a>
                <a href="View/php/helper/helper_data_export.php?type=item" type="button" class="btn btn-sm btn-outline-secondary">Export</a>
            </div>
            </div>
</div>
<?php
            $itemController = new ItemController();
            $authCheck = new Authorisation();
            $result = $itemController->getAllItems();

            if(odbc_num_rows($result) == 0){
              echo "<div class='alert alert-warning' role='alert'>
              Es sind keine Items erfasst
              </div>";
            }elseif($authCheck->checkAuthorisation("items_edit") == 0){
              echo "<div class='alert alert-warning' role='alert'>
              Sie haben keine Berechtigung diese Seite aufzurufen.
              </div>";
            }
            else
            {
              echo "<div class='table-responsive'>
              <table class='table table-striped table-sm' id='emp_table'>
              <thead>
                  <tr>
                  <th scope='col'>ID</th>
                  <th scope='col'>Typ</th>
                  <th scope='col'>Identifikation</th>
                  <th scope='col'>Name / Hersteller</th>
                  <th scope='col'> </th>
                  </tr>
              </thead>
              <tbody>";
           
            while(odbc_fetch_row($result)) {
                echo "<tr>";
                echo"<td>".odbc_result($result, "id")."</td>
                    <td>".odbc_result($result, "type")."</td>
                    <td>".odbc_result($result, "factorynr")."</td>
                    <td>".odbc_result($result, "name")."</td>";

                if($authCheck->checkAuthorisation("items_edit") == 1){
                    echo "<td><a href='?view=edititem&id=".odbc_result($result, "id")."' class='btn btn-info'>Bearbeiten</a></td>";
                }
                echo "</tr>";
            }
          }
            ?>

            </tbody>
            </table>
</div>