<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
            <h1 class="h2">Meine Items</h1>
            <div class="btn-toolbar mb-2 mb-md-0">
            <div class="btn-group me-2">
                <a href="View/php/helper/helper_data_export.php?type=myitems" type="button" class="btn btn-sm btn-outline-secondary">Export</a>
            </div>
            </div>
</div>
<?php
            $itemController = new ItemController();
            $authCheck = new Authorisation();
            $username = $_SESSION['userobj'];
            $result = $itemController->getMyItems($username);

            if(odbc_num_rows($result) == 0){
              echo "<div class='alert alert-warning' role='alert'>
              Ihnen sind keine Items zugewiesen
              </div>";
            }
            else
            {
              echo "<div class='table-responsive'>
              <table class='table table-striped table-sm' id='emp_table'>
              <thead>
                  <tr>
                  <th scope='col'>Typ</th>
                  <th scope='col'>Identifikation</th>
                  <th scope='col'>Name / Hersteller</th>
                  <th scope='col'>Zugewiesen am</th>
                  <th scope='col'>Retourniert am</th>
                  <th scope='col'>Status</th>
                  </tr>
              </thead>
              <tbody>";
           
            while(odbc_fetch_row($result)) {
                echo "<tr>";
                echo"<td>".odbc_result($result, "type")."</td>
                    <td>".odbc_result($result, "factorynr")."</td>
                    <td>".odbc_result($result, "name")."</td>
                    <td>".odbc_result($result, "recieved")."</td>
                    <td>".odbc_result($result, "returned")."</td>
                    <td>".odbc_result($result, "status")."</td>";
                echo "</tr>";
            }
          }
            ?>

            </tbody>
            </table>
</div>